
SET(LIBMV_VERSION_MAJOR 0)
SET(LIBMV_VERSION_MINOR 1)

# The standard GNU version numbering scheme is major.minor.revision
FIND_PACKAGE(Subversion)
IF(Subversion_FOUND)
  Subversion_WC_INFO(${CMAKE_CURRENT_SOURCE_DIR} ER)
  SET(SUBVERSION_REVISION ${ER_WC_REVISION})
ENDIF(Subversion_FOUND)
SET(LIBMV_VERSION_PATCH ${SUBVERSION_REVISION})

# Built from svn
SET(LIBMV_VERSION "${LIBMV_VERSION_MAJOR}.${LIBMV_VERSION_MINOR}.${LIBMV_VERSION_PATCH}")
# Alpha version [+number]
# SET(LIBMV_VERSION "${LIBMV_VERSION_MAJOR}.${LIBMV_VERSION_MINOR}-a")
# Beta version [+number]
# SET(LIBMV_VERSION "${LIBMV_VERSION_MAJOR}.${LIBMV_VERSION_MINOR}-b")
# Release candidate version [+number]
# SET(LIBMV_VERSION "${LIBMV_VERSION_MAJOR}.${LIBMV_VERSION_MINOR}-rc")

ADD_DEFINITIONS('-DLIBMV_VERSION_MAJOR=${LIBMV_VERSION_MAJOR}')
ADD_DEFINITIONS('-DLIBMV_VERSION_MINOR=${LIBMV_VERSION_MINOR}')
ADD_DEFINITIONS('-DLIBMV_VERSION_PATCH=${LIBMV_VERSION_PATCH}')
ADD_DEFINITIONS('-DLIBMV_VERSION="${LIBMV_VERSION}"')