
SET(CPACK_PACKAGE_VERSION ${LIBMV_VERSION})
SET(CPACK_PACKAGE_VERSION_MAJOR ${LIBMV_VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${LIBMV_VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${LIBMV_VERSION_PATCH})

SET(CPACK_SOURCE_GENERATOR "TBZ2;DEB;RPM;")

SET(CPACK_SOURCE_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${LIBMV_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")

SET(CPACK_PACKAGE_NAME "libmv")
SET(CPACK_PACKAGE_DESCRIPTION "A structure-from-motion library")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A structure-from-motion library for match moving, tracking etc.")
SET(CPACK_RESOURCE_FILE_LICENSE "${LIBMV_SOURCE_DIR}/../LICENSE")

SET(CPACK_SOURCE_IGNORE_FILES
  "/build/;/.svn/;~$;${CPACK_SOURCE_IGNORE_FILES}")

ADD_CUSTOM_TARGET(dist COMMAND ${CMAKE_MAKE_PROGRAM} package_source)

INCLUDE(CPack)

# TODO(julien) Finish this!!!! Ex:
# INCLUDE(UseRPMTools)
# IF(RPMTools_FOUND)
#   RPMTools_ADD_RPM_TARGETS(${PROJECT_NAME})
# ENDIF(RPMTools_FOUND)
# 
# set(CPACK_INSTALL_CMAKE_PROJECTS "${LIBMV_BINARY_DIR}" "LIBMV" "ALL" "/")
# set(CPACK_PACKAGE_INSTALL_DIRECTORY "LIBMV")
# #set(CPACK_PACKAGE_ICON "${LIBMV_SOURCE_DIR}\\\\libmv-logo.png")
# set(CPACK_PACKAGE_CONTACT "Libmv Team <XXX@XXX.org>")
# set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr \\\${WriteEnvStr_RegKey} \\\"LIBMV_HOME\\\" $INSTDIR")
# set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.3.6), libgcc1 (>= 1:4.1)")
# configure_file(${CMAKE_CURRENT_SOURCE_DIR}/cmake/revision.h.in ${CMAKE_CURRENT_BINARY_DIR}/revision.h)